[build]
  # Força o Netlify a entrar na pasta do frontend, instalar tudo do zero e rodar o build
  command = "cd frontend && npm install && npm run build"
  # Mostra exatamente onde a pasta gerada vai estar a partir da raiz total
  publish = "frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200