[build]
  # Força o Netlify a usar apenas o Node.js e ignorar completamente o Python/Pip
  environment = { PYTHON_VERSION = "none" }
  
  # Comando direto para entrar na pasta do React e gerar o build
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200