# Generated by Django 6.0.6 on 2026-06-24 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glicemia', '0002_medicamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxaCorrecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glicemia_min', models.IntegerField()),
                ('glicemia_max', models.IntegerField(blank=True, null=True)),
                ('dose_ui', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxas_correcao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
