# Generated by Django 6.0.6 on 2026-07-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glicemia', '0004_remove_medicao_notas_medicao_notes_perfilmedico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmedico',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='tipo',
            field=models.CharField(choices=[('Jejum', 'Jejum'), ('Pre-Prandial', 'Antes da refeição'), ('Pos-Prandial', 'Após a refeição'), ('Antes-Dormir', 'Antes de Dormir'), ('Outro', 'Outro')], max_length=20),
        ),
    ]
